// ? Fichier utilisé pour les svg de technos.
// ? Utilisé dans <Select />

export const technosPath = {
  html: '/images/technos/html.svg',
  css: '/images/technos/css.svg',
  javascript: '/images/technos/javascript.svg',
  react: '/images/technos/react.svg',
  ejs: '/images/technos/ejs.svg',
  github: '/images/technos/github.svg',
  graphql: '/images/technos/graphql.svg',
  insomnia: '/images/technos/insomnia.svg',
  nodejs: '/images/technos/nodejs.svg',
  postgresql: '/images/technos/postgresql.svg',
  redux: '/images/technos/redux.svg',
  sequelize: '/images/technos/sequelize.svg',
  strapi: '/images/technos/strapi.svg',
  typescript: '/images/technos/typescript.svg',
  vite: '/images/technos/vite.svg',
  vuejs: '/images/technos/vuejs.svg',
};

export const technos = [
  {
    id: 'html',

    label: 'Html',
    name: 'Html',
    value: 'Html',
    path: technosPath.html,
  },
  {
    id: 'css',
    label: 'Css',
    name: 'Css',
    value: 'Css',
    path: technosPath.css,
  },
  {
    id: 'javascript',
    label: 'Javascript',
    name: 'Javascript',
    value: 'Javascript',
    path: technosPath.javascript,
  },
  {
    id: 'react',
    label: 'React',
    name: 'React',
    value: 'React',
    path: technosPath.react,
  },
  {
    id: 'ejs',
    label: 'Ejs',
    name: 'Ejs',
    value: 'Ejs',
    path: technosPath.ejs,
  },
  {
    id: 'github',
    label: 'Github',
    name: 'Github',
    value: 'Github',
    path: technosPath.github,
  },
  {
    id: 'graphql',
    label: 'Graphql',
    name: 'Graphql',
    value: 'Graphql',
    path: technosPath.graphql,
  },
  {
    id: 'insomnia',
    label: 'Insomnia',
    name: 'Insomnia',
    value: 'Insomnia',
    path: technosPath.insomnia,
  },
  {
    id: 'nodejs',
    label: 'Nodejs',
    name: 'Nodejs',
    value: 'Nodejs',
    path: technosPath.nodejs,
  },
  {
    id: 'postgresql',
    label: 'Postgresql',
    name: 'Postgresql',
    value: 'Postgresql',
    path: technosPath.postgresql,
  },
  {
    id: 'redux',
    label: 'Redux',
    name: 'Redux',
    value: 'Redux',
    path: technosPath.redux,
  },
  {
    id: 'sequelize',
    label: 'Sequelize',
    name: 'Sequelize',
    value: 'Sequelize',
    path: technosPath.sequelize,
  },
  {
    id: 'strapi',
    label: 'Strapi',
    name: 'Strapi',
    value: 'Strapi',
    path: technosPath.strapi,
  },
  {
    id: 'typescript',
    label: 'Typescript',
    name: 'Typescript',
    value: 'Typescript',
    path: technosPath.typescript,
  },
  {
    id: 'vite',
    label: 'Vite',
    name: 'Vite',
    value: 'Vite',
    path: technosPath.vite,
  },
  {
    id: 'vuejs',
    label: 'Vuejs',
    name: 'Vuejs',
    value: 'Vuejs',
    path: technosPath.vuejs,
  },
];
